{@i == 1}?{
  IF OBJECT_ID('@target_database_schema.@target_table_1') IS NOT NULL
    DROP TABLE @target_database_schema.@target_table_1;

    IF OBJECT_ID('@target_database_schema.@target_table_2') IS NOT NULL
    DROP TABLE @target_database_schema.@target_table_2;

  CREATE TABLE @target_database_schema.@target_table_1 (
    DB  VARCHAR(10),
    COHORT_DEFINITION_ID  INT,
    COHORT_OF_INTEREST  VARCHAR(500),
    T2DM  VARCHAR(10),
    COHORT_COUNT  INT,
    PERSON_COUNT INT,
    PCT  FLOAT
  );

    CREATE TABLE @target_database_schema.@target_table_2 (
    DB  VARCHAR(10),
    COHORT_DEFINITION_ID  INT,
    COHORT_OF_INTEREST  VARCHAR(500),
    T2DM  VARCHAR(10),
    INGREDIENT_CONCEPT_ID_1 INT,
    INGREDIENT_CONCEPT_NAME_1 VARCHAR(150),
    INGREDIENT_CONCEPT_ID_2 INT,
    INGREDIENT_CONCEPT_NAME_2 VARCHAR(150),
    PERSON_COUNT INT
  );
}

IF OBJECT_ID('tempdb..#TEMP_CTE_COHORT_DRUG') IS NOT NULL
  DROP TABLE tempdb..#TEMP_CTE_COHORT_DRUG;


WITH CTE_COHORTS_OF_INTEREST AS (
	SELECT *
	FROM @target_database_schema.@cohort_universe u
	WHERE EXPOSURE_COHORT = 1
	AND FU_STRAT_ITT_PP0DAY = 1
	AND T2DM = 'NARROW'
	AND COHORT_OF_INTEREST != 'SGLT2i'
	AND COHORT_DEFINITION_ID != 74 /*EXCLUDE METFORMIN*/
	AND COHORT_DEFINITION_ID < 100 /*Excludes other SGLT2Is*/
),
CTE_INDEX_DRUG_CODE_LIST AS (
	/*Ingredients are in there*/
	SELECT DISTINCT u.*, cl.*
	FROM CTE_COHORTS_OF_INTEREST u
		JOIN @target_database_schema.@code_list cl
			ON cl.CODE_LIST_NAME = u.COHORT_OF_INTEREST
),
CTE_COHORT_DRUG AS (
	/*Find what was prescribed on day 1*/
	SELECT DISTINCT c.COHORT_DEFINITION_ID, u.COHORT_OF_INTEREST, u.T2DM, c.SUBJECT_ID, c.COHORT_START_DATE, de.DRUG_CONCEPT_ID, id.CONCEPT_NAME
	FROM @target_database_schema.@cohort_table c
		JOIN CTE_COHORTS_OF_INTEREST  u
			ON u.COHORT_DEFINITION_ID = c.COHORT_DEFINITION_ID
		JOIN CTE_INDEX_DRUG_CODE_LIST id
			ON id.COHORT_DEFINITION_ID = c.COHORT_DEFINITION_ID
		JOIN @cdm_database_schema.DRUG_ERA de
			ON de.DRUG_CONCEPT_ID = id.CONCEPT_ID
			AND de.PERSON_ID = c.SUBJECT_ID
			AND de.DRUG_ERA_START_DATE = c.COHORT_START_DATE
)
SELECT '@dbID' AS DB, *
INTO #TEMP_CTE_COHORT_DRUG
FROM CTE_COHORT_DRUG;



INSERT @target_database_schema.@target_table_1 (DB, COHORT_DEFINITION_ID, COHORT_OF_INTEREST, T2DM, COHORT_COUNT, PERSON_COUNT, PCT)
SELECT d1.DB, d1.COHORT_DEFINITION_ID, d1.COHORT_OF_INTEREST, d1.T2DM,
  COUNT(DISTINCT d1.SUBJECT_ID) AS COHORT_COUNT,
  COUNT(DISTINCT d2.SUBJECT_ID) AS PERSON_COUNT,
  COUNT(DISTINCT d2.SUBJECT_ID)*1.0 / COUNT(DISTINCT d1.SUBJECT_ID) AS PCT
FROM #TEMP_CTE_COHORT_DRUG d1
  LEFT OUTER JOIN #TEMP_CTE_COHORT_DRUG d2
  	ON d1.DB = d2.DB
  	AND d1.SUBJECT_ID = d2.SUBJECT_ID
		AND d1.COHORT_START_DATE = d2.COHORT_START_DATE
		AND d1.COHORT_DEFINITION_ID != d2.COHORT_DEFINITION_ID
		AND d1.DRUG_CONCEPT_ID != d2.DRUG_CONCEPT_ID
GROUP BY d1.DB, d1.COHORT_DEFINITION_ID, d1.COHORT_OF_INTEREST, d1.T2DM;



INSERT @target_database_schema.@target_table_2 (DB, COHORT_DEFINITION_ID, COHORT_OF_INTEREST, T2DM, INGREDIENT_CONCEPT_ID_1, INGREDIENT_CONCEPT_NAME_1, INGREDIENT_CONCEPT_ID_2, INGREDIENT_CONCEPT_NAME_2, PERSON_COUNT)
SELECT d1.DB, d1.COHORT_DEFINITION_ID, d1.COHORT_OF_INTEREST, d1.T2DM,
	d1.DRUG_CONCEPT_ID AS INGREDIENT_CONCEPT_ID_1,
	d1.CONCEPT_NAME AS INGREDIENT_CONCEPT_NAME_1,
	d2.DRUG_CONCEPT_ID AS INGREDIENT_CONCEPT_ID_2,
	d2.CONCEPT_NAME AS INGREDIENT_CONCEPT_ID_2,
	COUNT(DISTINCT d2.SUBJECT_ID) AS PERSON_COUNT
FROM #TEMP_CTE_COHORT_DRUG d1
  JOIN #TEMP_CTE_COHORT_DRUG d2
		ON d1.DB = d2.DB
		AND d1.SUBJECT_ID = d2.SUBJECT_ID
		AND d1.COHORT_START_DATE = d2.COHORT_START_DATE
		AND d1.COHORT_DEFINITION_ID != d2.COHORT_DEFINITION_ID
		AND d1.DRUG_CONCEPT_ID != d2.DRUG_CONCEPT_ID
GROUP BY d1.DB, d1.COHORT_DEFINITION_ID, d1.COHORT_OF_INTEREST, d1.T2DM,
	d1.DRUG_CONCEPT_ID, d1.CONCEPT_NAME,
	d2.DRUG_CONCEPT_ID, d2.CONCEPT_NAME;
