{@i == 1}?{
  IF OBJECT_ID('@target_database_schema.@target_table') IS NOT NULL
    DROP TABLE @target_database_schema.@target_table;

  CREATE TABLE @target_database_schema.@target_table (
    DB                        VARCHAR(10),
    COHORT_DEFINITION_ID      INT,
    FULL_NAME                 VARCHAR(100),
    COUNT_DKA_PEOPLE          INT,
    COUNT_GLUCOSE_PEOPLE      INT,
    COUNT_BICARBONATE_PEOPLE  INT,
    COUNT_KETONE_PEOPLE       INT,
    COUNT_PEOPLE_WITH_3_TESTS INT,
    PCT_DKA_PEOPLE_WITH_3_TESTS FLOAT
  );
}

IF OBJECT_ID('tempdb..#temp_results') IS NOT NULL
  DROP TABLE tempdb..#temp_results;

WITH CTE_PEOPLE AS (
	SELECT s.*, op.OBSERVATION_PERIOD_START_DATE, op.OBSERVATION_PERIOD_END_DATE, u.FULL_NAME
	FROM @target_database_schema.@cohort_table s
		JOIN @cdm_database_schema.OBSERVATION_PERIOD op
			ON op.PERSON_ID = s.SUBJECT_ID
			AND s.COHORT_START_DATE BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
		JOIN @target_database_schema.@cohort_universe u
			ON u.COHORT_DEFINITION_ID = s.COHORT_DEFINITION_ID
	WHERE s.COHORT_DEFINITION_ID IN (
		SELECT DISTINCT COHORT_DEFINITION_ID
		FROM @target_database_schema.@cohort_universe
		WHERE EXPOSURE_COHORT = 1
		AND FU_STRAT_ITT_PP0DAY = 1
	)
),
CTE_DKA_PEOPLE AS (
	SELECT c2.COHORT_DEFINITION_ID, c2.FULL_NAME, c1.SUBJECT_ID, MIN(c1.COHORT_START_DATE) AS DKA_INDEX
	FROM @target_database_schema.@cohort_table c1
		JOIN CTE_PEOPLE c2
			ON c1.SUBJECT_ID = c2.SUBJECT_ID
			AND c2.COHORT_START_DATE < c1.COHORT_START_DATE
			AND c1.COHORT_START_DATE BETWEEN c2.OBSERVATION_PERIOD_START_DATE AND c2.OBSERVATION_PERIOD_END_DATE
	WHERE c1.COHORT_DEFINITION_ID IN (200)
	GROUP BY c2.COHORT_DEFINITION_ID, c2.FULL_NAME, c1.SUBJECT_ID
),
CTE_MEASUREMENTS_GLUCOSE AS (
	SELECT dp.*, m.*
	FROM @cdm_database_schema.MEASUREMENT M
		JOIN @cdm_database_schema.CONCEPT c
			ON c.CONCEPT_ID = m.MEASUREMENT_CONCEPT_ID
		JOIN CTE_PEOPLE p
			ON p.SUBJECT_ID = m.PERSON_ID
			AND m.MEASUREMENT_DATE BETWEEN p.OBSERVATION_PERIOD_START_DATE AND p.OBSERVATION_PERIOD_END_DATE
		JOIN CTE_DKA_PEOPLE dp
			ON dp.SUBJECT_ID = m.PERSON_ID
			AND dp.COHORT_DEFINITION_ID = p.COHORT_DEFINITION_ID
			AND M.MEASUREMENT_DATE BETWEEN DATEADD(D,-30,dp.DKA_INDEX) AND DATEADD(D,30,dp.DKA_INDEX)
	WHERE MEASUREMENT_CONCEPT_ID IN (
		SELECT CONCEPT_ID
		FROM @target_database_schema.@code_list
		WHERE CODE_LIST_NAME = 'Glucose'
	)
	AND VALUE_AS_NUMBER NOT IN ('', 9999999.0)
	AND UNIT_SOURCE_VALUE IS NOT NULL
	AND UNIT_SOURCE_VALUE NOT IN ('NULL')
),
CTE_MEASUREMENTS_BICARBONATE AS (
	SELECT dp.*, m.*
	FROM @cdm_database_schema.MEASUREMENT M
		JOIN @cdm_database_schema.CONCEPT c
			ON c.CONCEPT_ID = m.MEASUREMENT_CONCEPT_ID
		JOIN CTE_PEOPLE p
			ON p.SUBJECT_ID = m.PERSON_ID
			AND m.MEASUREMENT_DATE BETWEEN p.OBSERVATION_PERIOD_START_DATE AND p.OBSERVATION_PERIOD_END_DATE
		JOIN CTE_DKA_PEOPLE dp
			ON dp.SUBJECT_ID = m.PERSON_ID
			AND dp.COHORT_DEFINITION_ID = p.COHORT_DEFINITION_ID
			AND M.MEASUREMENT_DATE BETWEEN DATEADD(D,-30,dp.DKA_INDEX) AND DATEADD(D,30,dp.DKA_INDEX)
	WHERE MEASUREMENT_CONCEPT_ID IN (
		SELECT CONCEPT_ID
		FROM @target_database_schema.@code_list
		WHERE CODE_LIST_NAME = 'Bicarbonate'
	)
	AND VALUE_AS_NUMBER NOT IN ('', 9999999.0)
	AND UNIT_SOURCE_VALUE IS NOT NULL
	AND UNIT_SOURCE_VALUE NOT IN ('NULL')
),
CTE_MEASUREMENTS_KETONE AS (
	SELECT dp.*, m.*
	FROM @cdm_database_schema.MEASUREMENT M
		JOIN @cdm_database_schema.CONCEPT c
			ON c.CONCEPT_ID = m.MEASUREMENT_CONCEPT_ID
		JOIN CTE_PEOPLE p
			ON p.SUBJECT_ID = m.PERSON_ID
			AND m.MEASUREMENT_DATE BETWEEN p.OBSERVATION_PERIOD_START_DATE AND p.OBSERVATION_PERIOD_END_DATE
		JOIN CTE_DKA_PEOPLE dp
			ON dp.SUBJECT_ID = m.PERSON_ID
			AND dp.COHORT_DEFINITION_ID = p.COHORT_DEFINITION_ID
			AND M.MEASUREMENT_DATE BETWEEN DATEADD(D,-30,dp.DKA_INDEX) AND DATEADD(D,30,dp.DKA_INDEX)
	WHERE MEASUREMENT_CONCEPT_ID IN (
		SELECT CONCEPT_ID
		FROM @target_database_schema.@code_list
		WHERE CODE_LIST_NAME = 'Ketone'
	)
	AND VALUE_AS_NUMBER NOT IN ('', 9999999.0)
	AND UNIT_SOURCE_VALUE IS NOT NULL
	AND UNIT_SOURCE_VALUE NOT IN ('NULL')
)
SELECT
  '@dbID' AS DB,
  p.COHORT_DEFINITION_ID, p.FULL_NAME,
	COUNT(DISTINCT p.SUBJECT_ID) AS COUNT_DKA_PEOPLE,
	COUNT(DISTINCT g.SUBJECT_ID) AS COUNT_GLUCOSE_PEOPLE,
	COUNT(DISTINCT b.SUBJECT_ID) AS COUNT_BICARBONATE_PEOPLE,
	COUNT(DISTINCT k.SUBJECT_ID) AS COUNT_KETONE_PEOPLE,
	COUNT(DISTINCT(CASE
		WHEN g.SUBJECT_ID IS NOT NULL AND b.SUBJECT_ID IS NOT NULL AND k.SUBJECT_ID IS NOT NULL THEN p.SUBJECT_ID ELSE NULL
		END)) AS COUNT_PEOPLE_WITH_3_TESTS,
	COUNT(DISTINCT(CASE
		WHEN g.SUBJECT_ID IS NOT NULL AND b.SUBJECT_ID IS NOT NULL AND k.SUBJECT_ID IS NOT NULL THEN p.SUBJECT_ID ELSE NULL
		END))*1.0 / COUNT(DISTINCT p.SUBJECT_ID) AS PCT_DKA_PEOPLE_WITH_3_TESTS
INTO #TEMP_RESULTS
FROM CTE_DKA_PEOPLE p
	LEFT OUTER JOIN CTE_MEASUREMENTS_GLUCOSE g
		ON p.COHORT_DEFINITION_ID = g.COHORT_DEFINITION_ID
		AND p.SUBJECT_ID = g.SUBJECT_ID
	LEFT OUTER JOIN CTE_MEASUREMENTS_BICARBONATE b
		ON p.COHORT_DEFINITION_ID = b.COHORT_DEFINITION_ID
		AND p.SUBJECT_ID = b.SUBJECT_ID
	LEFT OUTER JOIN CTE_MEASUREMENTS_KETONE k
		ON p.COHORT_DEFINITION_ID = k.COHORT_DEFINITION_ID
		AND p.SUBJECT_ID = k.SUBJECT_ID
GROUP BY p.COHORT_DEFINITION_ID, p.FULL_NAME;


INSERT INTO @target_database_schema.@target_table (DB,COHORT_DEFINITION_ID,FULL_NAME,COUNT_DKA_PEOPLE,COUNT_GLUCOSE_PEOPLE,COUNT_BICARBONATE_PEOPLE,COUNT_KETONE_PEOPLE,COUNT_PEOPLE_WITH_3_TESTS, PCT_DKA_PEOPLE_WITH_3_TESTS)
SELECT DB,COHORT_DEFINITION_ID,FULL_NAME,COUNT_DKA_PEOPLE,COUNT_GLUCOSE_PEOPLE,COUNT_BICARBONATE_PEOPLE,COUNT_KETONE_PEOPLE,COUNT_PEOPLE_WITH_3_TESTS, PCT_DKA_PEOPLE_WITH_3_TESTS
FROM #TEMP_RESULTS;

