  IF OBJECT_ID('@target_database_schema.@target_table') IS NOT NULL
    DROP TABLE @target_database_schema.@target_table;

IF OBJECT_ID('tempdb..#temp_results') IS NOT NULL
  DROP TABLE tempdb..#temp_results;

WITH CTE_TABLE_SHELL AS (
	SELECT DISTINCT
		STAT_ORDER_NUMBER_1,
		CASE
			WHEN STAT_ORDER_NUMBER_1 = 1 THEN 1
			WHEN STAT_ORDER_NUMBER_1 = 3 THEN 2
			WHEN STAT_ORDER_NUMBER_1 = 2 THEN 3
			WHEN STAT_ORDER_NUMBER_1 = 5 THEN 5
			WHEN STAT_ORDER_NUMBER_1 = 7 THEN 7
			WHEN STAT_ORDER_NUMBER_1 = 8 THEN 8
			WHEN STAT_ORDER_NUMBER_1 = 9 THEN 9
			WHEN STAT_ORDER_NUMBER_1 = 10 THEN 10
			WHEN STAT_ORDER_NUMBER_1 = 11 THEN 12
			ELSE STAT_ORDER_NUMBER_1
		END AS STAT_ORDER_NUMBER_1_UPDATED,
		STAT_ORDER_NUMBER_2,
		STAT_TYPE,
		CASE
			WHEN STAT_TYPE = 'Female' THEN 'Gender, % of female'
			WHEN STAT_TYPE = 'First Insulin Prescriptions Before (<) but not After' THEN 'Before, %'
			WHEN STAT_TYPE = 'First Insulin Prescriptions Neither Before or After (Includes Index)' THEN 'None, %'
			WHEN STAT_TYPE = 'First Insulin Prescriptions After (>) but not Before' THEN 'After, %'
			WHEN STAT_TYPE = 'First Insulin Prescriptions On Index' THEN 'On Index, %'
			WHEN STAT_TYPE = 'Index to DKA:  Mean (SD) days' THEN 'Days from index to DKA: mean (SD)'
			WHEN STAT_TYPE LIKE 'Precipitating Events (w/in 30 days of DKA):%' THEN CONCAT(REPLACE(STAT_TYPE,'Precipitating Events (w/in 30 days of DKA):  ',''),', %')
			ELSE STAT_TYPE
		END AS STAT_TYPE_UPDATED
	FROM @target_database_schema.@tablePotentialRiskFactors
	WHERE STAT_ORDER_NUMBER_1 IN (
		1,2,5,7,8,9,11
	)
	OR (STAT_ORDER_NUMBER_1 = 3 AND STAT_ORDER_NUMBER_2 = 0)
	OR (STAT_ORDER_NUMBER_1 = 10 AND STAT_ORDER_NUMBER_2 = 1)
	UNION ALL
	SELECT 0 AS STAT_ORDER_NUMBER_1, 0 AS STAT_ORDER_NUMBER_1_UPDATED, 0 AS STAT_ORDER_NUMBER_2, '' AS STAT_TYPE, 'Exposure Cohort' AS STAT_TYPE_UDPATED
	UNION ALL
	SELECT 0 AS STAT_ORDER_NUMBER_1, 4 AS STAT_ORDER_NUMBER_1_UPDATED, 0 AS STAT_ORDER_NUMBER_2, '' AS STAT_TYPE, 'First Insulin prescription relative to index date' AS STAT_TYPE_UDPATED
	UNION ALL
	SELECT 0 AS STAT_ORDER_NUMBER_1, 6 AS STAT_ORDER_NUMBER_1_UPDATED, 0 AS STAT_ORDER_NUMBER_2, '' AS STAT_TYPE, 'Comorbidity scores' AS STAT_TYPE_UDPATED
	UNION ALL
	SELECT 0 AS STAT_ORDER_NUMBER_1, 11 AS STAT_ORDER_NUMBER_1_UPDATED, 0 AS STAT_ORDER_NUMBER_2, '' AS STAT_TYPE, 'Preceding events within 30 days' AS STAT_TYPE_UDPATED
),
CTE_TABLE_SHELL_DKA AS (
	SELECT 1 AS DKA
	UNION ALL
	SELECT 0 AS DKA
),
CTE_COHORTS AS (
	SELECT DISTINCT u.COHORT_OF_INTEREST
	FROM @target_database_schema.@cohort_universe u
	WHERE u.COHORT_OF_INTEREST IN (
		'SGLT2i','SU','DPP-4i','GLP-1a','TZDs','Insulin','Metformin','Insulinotropic AHAs'
	)
),
CTE_FULL_TABLE_SHELL AS (
	SELECT COHORT_OF_INTEREST, DKA, STAT_ORDER_NUMBER_1, STAT_ORDER_NUMBER_1_UPDATED, STAT_ORDER_NUMBER_2, STAT_TYPE,
		CASE
			WHEN STAT_TYPE_UPDATED = 'Exposure Cohort' THEN COHORT_OF_INTEREST
			ELSE STAT_TYPE_UPDATED
		END STAT_TYPE_UPDATED
	FROM CTE_COHORTS, CTE_TABLE_SHELL_DKA, CTE_TABLE_SHELL
)
SELECT s.*,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f1.STAT AS VARCHAR(100))
		WHEN f1.STAT_OTHER IS NOT NULL THEN f1.STAT_OTHER
		WHEN f1.STAT IS NOT NULL THEN CAST(CAST(f1.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f1.STAT_OTHER IS NULL THEN CAST(f1.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS CCAE_BROAD,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f2.STAT AS VARCHAR(100))
		WHEN f2.STAT_OTHER IS NOT NULL THEN f2.STAT_OTHER
		WHEN f2.STAT IS NOT NULL THEN CAST(CAST(f2.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f2.STAT_OTHER IS NULL THEN CAST(f2.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS CCAE_NARROW,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f5.STAT AS VARCHAR(100))
		WHEN f5.STAT_OTHER IS NOT NULL THEN f5.STAT_OTHER
		WHEN f5.STAT IS NOT NULL THEN CAST(CAST(f5.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f5.STAT_OTHER IS NULL THEN CAST(f5.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS MDCD_BROAD,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f6.STAT AS VARCHAR(100))
		WHEN f6.STAT_OTHER IS NOT NULL THEN f6.STAT_OTHER
		WHEN f6.STAT IS NOT NULL THEN CAST(CAST(f6.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f6.STAT_OTHER IS NULL THEN CAST(f6.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS MDCD_NARROW,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f3.STAT AS VARCHAR(100))
		WHEN f3.STAT_OTHER IS NOT NULL THEN f3.STAT_OTHER
		WHEN f3.STAT IS NOT NULL THEN CAST(CAST(f3.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f3.STAT_OTHER IS NULL THEN CAST(f3.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS MDCR_BROAD,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f4.STAT AS VARCHAR(100))
		WHEN f4.STAT_OTHER IS NOT NULL THEN f4.STAT_OTHER
		WHEN f4.STAT IS NOT NULL THEN CAST(CAST(f4.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f4.STAT_OTHER IS NULL THEN CAST(f4.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS MDCR_NARROW,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f7.STAT AS VARCHAR(100))
		WHEN f7.STAT_OTHER IS NOT NULL THEN f7.STAT_OTHER
		WHEN f7.STAT IS NOT NULL THEN CAST(CAST(f7.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f7.STAT_OTHER IS NULL THEN CAST(f7.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS OPTUM_SES_BROAD,
	CASE
		WHEN STAT_TYPE_UPDATED = 'Total Persons' THEN CAST(f8.STAT AS VARCHAR(100))
		WHEN f8.STAT_OTHER IS NOT NULL THEN f8.STAT_OTHER
		WHEN f8.STAT IS NOT NULL THEN CAST(CAST(f8.STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100))
		WHEN f8.STAT_OTHER IS NULL THEN CAST(f8.STAT AS VARCHAR(100))
		ELSE 'ERROR'
	END AS OPTUM_SES_NARROW
INTO #TEMP_RESULTS
FROM CTE_FULL_TABLE_SHELL s
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f1
		ON f1.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f1.DKA = s.DKA
		AND f1.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f1.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f1.DB = 'CCAE'
		AND f1.T2DM = 'BROAD'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f2
		ON f2.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f2.DKA = s.DKA
		AND f2.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f2.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f2.DB = 'CCAE'
		AND f2.T2DM = 'NARROW'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f3
		ON f3.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f3.DKA = s.DKA
		AND f3.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f3.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f3.DB = 'MDCR'
		AND f3.T2DM = 'BROAD'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f4
		ON f4.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f4.DKA = s.DKA
		AND f4.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f4.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f4.DB = 'MDCR'
		AND f4.T2DM = 'NARROW'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f5
		ON f5.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f5.DKA = s.DKA
		AND f5.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f5.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f5.DB = 'MDCD'
		AND f5.T2DM = 'BROAD'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f6
		ON f6.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f6.DKA = s.DKA
		AND f6.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f6.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f6.DB = 'MDCD'
		AND f6.T2DM = 'NARROW'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f7
		ON f7.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f7.DKA = s.DKA
		AND f7.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f7.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f7.DB = 'OPTUM_SES'
		AND f7.T2DM = 'BROAD'
	LEFT OUTER JOIN @target_database_schema.@tablePotentialRiskFactors f8
		ON f8.COHORT_OF_INTEREST = s.COHORT_OF_INTEREST
		AND f8.DKA = s.DKA
		AND f8.STAT_ORDER_NUMBER_1 = s.STAT_ORDER_NUMBER_1
		AND f8.STAT_ORDER_NUMBER_2 = s.STAT_ORDER_NUMBER_2
		AND f8.DB = 'OPTUM_SES'
		AND f8.T2DM = 'NARROW';

SELECT DKA,
  CASE
    WHEN COHORT_OF_INTEREST = 'SGLT2i' THEN 1
    WHEN COHORT_OF_INTEREST = 'SU' THEN 2
    WHEN COHORT_OF_INTEREST = 'DPP-4i' THEN 3
    WHEN COHORT_OF_INTEREST = 'GLP-1a' THEN 4
    WHEN COHORT_OF_INTEREST = 'TZDs' THEN 5
    WHEN COHORT_OF_INTEREST = 'Insulin' THEN 6
    WHEN COHORT_OF_INTEREST = 'Metformin' THEN 7
    WHEN COHORT_OF_INTEREST = 'Insulinotropic AHAs' THEN 8
  END AS STAT_ORDER_NUMBER_0,
  COHORT_OF_INTEREST, STAT_ORDER_NUMBER_1, STAT_ORDER_NUMBER_1_UPDATED, STAT_ORDER_NUMBER_2, STAT_TYPE, STAT_TYPE_UPDATED, CCAE_BROAD, CCAE_NARROW, MDCD_BROAD, MDCD_NARROW, MDCR_BROAD, MDCR_NARROW, OPTUM_SES_BROAD, OPTUM_SES_NARROW
INTO @target_database_schema.@target_table
FROM #temp_results;
