IF OBJECT_ID('@target_database_schema.@target_table') IS NOT NULL
  DROP TABLE @target_database_schema.@target_table;

IF OBJECT_ID('tempdb..#temp_results') IS NOT NULL
  DROP TABLE tempdb..#temp_results;

WITH CTE_COHORTS AS (
	SELECT T2DM,
		CASE
			WHEN TARGET_COHORT = 1 THEN 'Target Cohort'
			WHEN COMPARATOR_COHORT = 1 THEN 'Comparator Cohort'
			ELSE 'ERROR'
		END AS COHORT_TYPE,
		COHORT_DEFINITION_ID, COHORT_OF_INTEREST
	FROM @target_database_schema.@cohort_universe u
	WHERE EXPOSURE_COHORT = 1
	AND FU_STRAT_ITT_PP0DAY = 1
),
CTE_DB AS (
	SELECT DISTINCT DB
	FROM @target_database_schema.@tablePotentialRiskFactors
),
CTE_UNIVERSE AS (
	SELECT *
	FROM CTE_COHORTS, CTE_DB
),
CTE_DKA AS (
	SELECT DB, COHORT_DEFINITION_ID, STAT AS PEOPLE_WITH_DKA
	FROM @target_database_schema.@tableDKAFatal
	WHERE STAT_ORDER_NUMBER = 1
),
CTE_DKA_FATAL AS (
	SELECT DB, COHORT_DEFINITION_ID, STAT AS PEOPLE_WITH_DKA_FATALITY,
		CONCAT(CAST(CAST(STAT_PCT * 100 AS DECIMAL(6,1)) AS VARCHAR(100)),'%') AS PCT
	FROM @target_database_schema.@tableDKAFatal
	WHERE STAT_ORDER_NUMBER = 2
),
CTE_PULL_DATA AS (
	SELECT u.COHORT_DEFINITION_ID, u.COHORT_TYPE, u.T2DM, u.COHORT_OF_INTEREST, u.DB,
		d.PEOPLE_WITH_DKA,
		f.PEOPLE_WITH_DKA_FATALITY,
		f.PCT
	FROM CTE_UNIVERSE u
		LEFT OUTER JOIN CTE_DKA d
			ON d.DB = u.DB
			AND d.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		LEFT OUTER JOIN CTE_DKA_FATAL f
			ON f.DB = u.DB
			AND f.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
)
SELECT
  CASE
    WHEN u.COHORT_OF_INTEREST = 'SGLT2i' THEN 1
    WHEN u.COHORT_OF_INTEREST = 'SU' THEN 2
    WHEN u.COHORT_OF_INTEREST = 'DPP-4i' THEN 3
    WHEN u.COHORT_OF_INTEREST = 'GLP-1a' THEN 4
    WHEN u.COHORT_OF_INTEREST = 'TZDs' THEN 5
    WHEN u.COHORT_OF_INTEREST = 'Insulin' THEN 6
    WHEN u.COHORT_OF_INTEREST = 'Metformin' THEN 7
    WHEN u.COHORT_OF_INTEREST = 'Insulinotropic AHAs' THEN 8
    WHEN u.COHORT_OF_INTEREST = 'Other AHAs' THEN 9
    WHEN u.COHORT_OF_INTEREST = 'Canagliflozin' THEN 10
    WHEN u.COHORT_OF_INTEREST = 'Dapagliflozin' THEN 11
    WHEN u.COHORT_OF_INTEREST = 'Empagliflozin' THEN 12
  END AS STAT_ORDER_NUMBER_0,
  u.COHORT_OF_INTEREST, u.DB,
	MAX(d1.PEOPLE_WITH_DKA) AS BROAD_PEOPLE_WITH_DKA,
	MAX(d1.PEOPLE_WITH_DKA_FATALITY) AS BROAD_PEOPLE_WITH_DKA_FATALITY,
	MAX(d1.PCT) AS BROAD_PCT,
	MAX(d2.PEOPLE_WITH_DKA) AS NARROW_PEOPLE_WITH_DKA,
	MAX(d2.PEOPLE_WITH_DKA_FATALITY) AS NARROW_PEOPLE_WITH_DKA_FATALITY,
	MAX(d2.PCT) AS NARROW_PCT
INTO #TEMP_RESULTS
FROM CTE_UNIVERSE u
	LEFT OUTER JOIN CTE_PULL_DATA d1
		ON d1.DB = u.DB
		AND d1.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		AND d1.T2DM = 'BROAD'
	LEFT OUTER JOIN CTE_PULL_DATA d2
		ON d2.DB = u.DB
		AND d2.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		AND d2.T2DM = 'NARROW'
GROUP BY u.COHORT_OF_INTEREST, u.DB;

SELECT *
INTO @target_database_schema.@target_table
FROM #TEMP_RESULTS;
