IF OBJECT_ID('@target_database_schema.@target_table') IS NOT NULL
  DROP TABLE @target_database_schema.@target_table;

IF OBJECT_ID('tempdb..#temp_results') IS NOT NULL
  DROP TABLE tempdb..#temp_results;

WITH CTE_COHORTS AS (
	SELECT T2DM,
		CASE
			WHEN TARGET_COHORT = 1 THEN 'Target Cohort'
			WHEN COMPARATOR_COHORT = 1 THEN 'Comparator Cohort'
			ELSE 'ERROR'
		END AS COHORT_TYPE,
		COHORT_DEFINITION_ID, COHORT_OF_INTEREST
	FROM @target_database_schema.@cohort_universe u
	WHERE EXPOSURE_COHORT = 1
	AND FU_STRAT_ITT_PP0DAY = 1
),
CTE_DB AS (
	SELECT DISTINCT DB
	FROM @target_database_schema.@tablePotentialRiskFactors
),
CTE_TABLE_UNIVERSE AS (
	SELECT *
	FROM CTE_COHORTS, CTE_DB
),
CTE_PERSON AS (
	SELECT DB, COHORT_DEFINITION_ID, SUM(STAT) AS PERSONS
	FROM @target_database_schema.@tablePotentialRiskFactors
	WHERE STAT_ORDER_NUMBER_1 IN (1)
	GROUP BY DB, COHORT_DEFINITION_ID
),
CTE_GENDER AS (
	SELECT DB, COHORT_DEFINITION_ID, SUM(STAT) AS PERSONS_F
	FROM @target_database_schema.@tablePotentialRiskFactors
	WHERE STAT_ORDER_NUMBER_1 IN (2)
	GROUP BY DB, COHORT_DEFINITION_ID
),
CTE_AGE_MEAN AS (
	SELECT DB, COHORT_DEFINITION_ID, STAT_OTHER
	FROM @target_database_schema.@tableMeanAge
),
CTE_PULL_DATA AS (
	SELECT u.T2DM, u.COHORT_TYPE, u.COHORT_DEFINITION_ID, u.COHORT_OF_INTEREST, u.DB,
		p.PERSONS,
		a.STAT_OTHER AS AGE_MEAN_SD,
		CONCAT(CAST(CAST(g.PERSONS_F*1.0/p.PERSONS*100 AS DECIMAL(6,1)) AS VARCHAR(100)),'%') AS GENDER_PCT_F
	FROM CTE_TABLE_UNIVERSE u
		LEFT OUTER JOIN CTE_PERSON p
			ON p.DB = u.DB
			AND p.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		LEFT OUTER JOIN CTE_GENDER g
			ON g.DB = u.DB
			AND g.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		LEFT OUTER JOIN CTE_AGE_MEAN a
			ON a.DB = u.DB
			AND a.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
)
SELECT u.COHORT_TYPE,  u.COHORT_OF_INTEREST, u.DB,
	MAX(pd1.PERSONS) AS BROAD_PERSONS,
	MAX(pd1.AGE_MEAN_SD) AS BROAD_AGE_MEAN_SD,
	MAX(pd1.GENDER_PCT_F) AS BROAD_GENDER_PCT_F,
	MAX(pd2.PERSONS) AS NARROW_PERSONS,
	MAX(pd2.AGE_MEAN_SD) AS NARROW_AGE_MEAN_SD,
	MAX(pd2.GENDER_PCT_F) AS NARROW_GENDER_PCT_F
INTO #TEMP_RESULTS
FROM CTE_TABLE_UNIVERSE u
	LEFT OUTER JOIN CTE_PULL_DATA pd1
		ON pd1.DB = u.DB
		AND pd1.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		AND pd1.T2DM = 'BROAD'
	LEFT OUTER JOIN CTE_PULL_DATA pd2
		ON pd2.DB = u.DB
		AND pd2.COHORT_DEFINITION_ID = u.COHORT_DEFINITION_ID
		AND pd2.T2DM = 'NARROW'
GROUP BY u.COHORT_TYPE, u.COHORT_OF_INTEREST, u.DB;

SELECT *
INTO @target_database_schema.@target_table
FROM #TEMP_RESULTS;
