# Copyright 2016 Observational Health Data Sciences and Informatics
#
# This file is part of KeppraAngioedema
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create the analyses details
#'
#' @details
#' This function creates files specifying the analyses that will be performed.
#'
#' @param outputFolder   Name of local folder to place results; make sure to use forward slashes (/)
#'
#' @export
createAnalysesDetails <- function(outputFolder) {

  angioedemaId <- 3
  negativeControlIds <- c(29056,
                          29735,
                          73842,
                          74396,
                          75344,
                          75576,
                          77650,
                          78786,
                          78804,
                          79072,
                          79903,
                          80217,
                          80494,
                          80665,
                          80951,
                          133141,
                          133228,
                          133834,
                          134453,
                          134461,
                          134898,
                          136773,
                          136937,
                          137057,
                          138387,
                          139099,
                          140480,
                          140949,
                          141663,
                          141932,
                          192367,
                          192606,
                          192964,
                          193016,
                          193326,
                          194997,
                          195562,
                          195588,
                          195873,
                          196162,
                          197032,
                          197320,
                          197684,
                          198075,
                          198199,
                          199067,
                          199876,
                          200528,
                          200588,
                          253796,
                          256722,
                          258180,
                          260134,
                          261326,
                          261880,
                          312437,
                          313792,
                          314054,
                          316993,
                          317109,
                          317585,
                          318800,
                          319843,
                          321596,
                          372409,
                          373478,
                          374914,
                          376103,
                          376415,
                          378160,
                          378424,
                          378425,
                          380731,
                          432436,
                          432851,
                          433163,
                          433440,
                          433516,
                          434056,
                          434926,
                          435459,
                          436027,
                          437409,
                          437833,
                          439080,
                          440328,
                          440358,
                          440448,
                          440814,
                          441284,
                          441589,
                          442013,
                          443344,
                          4002650,
                          4193869,
                          4205509,
                          4291005,
                          4311499,
                          4324765,
                          43531027)
  excludedCovariateConceptIds <- c(702773,
                                   711584,
                                   711585,
                                   711586,
                                   711587,
                                   711588,
                                   711589,
                                   711615,
                                   711620,
                                   711621,
                                   711644,
                                   711645,
                                   734514,
                                   734519,
                                   734543,
                                   740910,
                                   740939,
                                   740940,
                                   740971,
                                   740992,
                                   740995,
                                   740996,
                                   740999,
                                   741000,
                                   741001,
                                   741022,
                                   19000857,
                                   19006201,
                                   19006202,
                                   19006235,
                                   19022290,
                                   19025782,
                                   19025783,
                                   19025784,
                                   19025785,
                                   19060002,
                                   19060401,
                                   19062939,
                                   19064833,
                                   19078781,
                                   19085062,
                                   19086166,
                                   19086167,
                                   19088478,
                                   19099448,
                                   19099449,
                                   19099450,
                                   19099461,
                                   19101553,
                                   19102504,
                                   19102835,
                                   19103081,
                                   19104539,
                                   19104540,
                                   19104541,
                                   19104542,
                                   19104549,
                                   19104550,
                                   19104551,
                                   19104602,
                                   19104603,
                                   19104604,
                                   19106807,
                                   19107017,
                                   19107287,
                                   19111376,
                                   19111377,
                                   19111378,
                                   19111379,
                                   19111380,
                                   19111381,
                                   19111382,
                                   19111383,
                                   19111386,
                                   19115093,
                                   19116034,
                                   19124115,
                                   19124116,
                                   19125803,
                                   19125804,
                                   19132401,
                                   19132402,
                                   19134946,
                                   19134947,
                                   19135179,
                                   19135378,
                                   40020027,
                                   40052545,
                                   40052546,
                                   40052547,
                                   40052548,
                                   40061698,
                                   40061699,
                                   40070681,
                                   40070682,
                                   40075252,
                                   40075255,
                                   40075257,
                                   40075258,
                                   40075259,
                                   40075260,
                                   40075261,
                                   40075262,
                                   40075263,
                                   40075264,
                                   40075265,
                                   40075266,
                                   40075267,
                                   40075270,
                                   40075271,
                                   40075272,
                                   40119293,
                                   40131124,
                                   40132106,
                                   40135474,
                                   40135475,
                                   40141414,
                                   40154738,
                                   40154739,
                                   40163204,
                                   40163205,
                                   40163206,
                                   40163207,
                                   40163208,
                                   40163209,
                                   40163210,
                                   40163211,
                                   40163212,
                                   40163213,
                                   40163214,
                                   40163215,
                                   40163218,
                                   40163219,
                                   40163220,
                                   40163221,
                                   40163222,
                                   40163223,
                                   40163228,
                                   40163229,
                                   40163230,
                                   40163231,
                                   40163232,
                                   40163233,
                                   40163234,
                                   40163235,
                                   40163236,
                                   40163237,
                                   40163238,
                                   40163241,
                                   40163243,
                                   40163244,
                                   40163245,
                                   40163246,
                                   40163251,
                                   40163252,
                                   40163253,
                                   40167308,
                                   40167309,
                                   40167310,
                                   40167311,
                                   40167313,
                                   40167314,
                                   40167315,
                                   40238910,
                                   40238911,
                                   40238912,
                                   40238920,
                                   40238921,
                                   40244397,
                                   40244398,
                                   40244399,
                                   40244400,
                                   40244401,
                                   40244402,
                                   42900977,
                                   42901023,
                                   42901024,
                                   42901025,
                                   42901674,
                                   42901704,
                                   42901705,
                                   42901706,
                                   42901707,
                                   42901708,
                                   42902608,
                                   45776841,
                                   45776842,
                                   45776843)

  dcos <- CohortMethod::createDrugComparatorOutcomes(targetId = 1,
                                                     comparatorId = 2,
                                                     excludedCovariateConceptIds = excludedCovariateConceptIds,
                                                     outcomeIds = c(angioedemaId,
                                                                    negativeControlIds))
  drugComparatorOutcomesList <- list(dcos)

  covarSettings <- FeatureExtraction::createCovariateSettings(useCovariateDemographics = TRUE,
                                                              useCovariateConditionOccurrence = TRUE,
                                                              useCovariateConditionOccurrence365d = TRUE,
                                                              useCovariateConditionOccurrence30d = TRUE,
                                                              useCovariateConditionOccurrenceInpt180d = TRUE,
                                                              useCovariateConditionEra = TRUE,
                                                              useCovariateConditionEraEver = TRUE,
                                                              useCovariateConditionEraOverlap = TRUE,
                                                              useCovariateConditionGroup = TRUE,
                                                              useCovariateDrugExposure = TRUE,
                                                              useCovariateDrugExposure365d = TRUE,
                                                              useCovariateDrugExposure30d = TRUE,
                                                              useCovariateDrugEra = TRUE,
                                                              useCovariateDrugEra365d = TRUE,
                                                              useCovariateDrugEra30d = TRUE,
                                                              useCovariateDrugEraEver = TRUE,
                                                              useCovariateDrugEraOverlap = TRUE,
                                                              useCovariateDrugGroup = TRUE,
                                                              useCovariateProcedureOccurrence = TRUE,
                                                              useCovariateProcedureOccurrence365d = TRUE,
                                                              useCovariateProcedureOccurrence30d = TRUE,
                                                              useCovariateProcedureGroup = TRUE,
                                                              useCovariateObservation = TRUE,
                                                              useCovariateObservation365d = TRUE,
                                                              useCovariateObservation30d = TRUE,
                                                              useCovariateObservationCount365d = TRUE,
                                                              useCovariateMeasurement365d = TRUE,
                                                              useCovariateMeasurement30d = TRUE,
                                                              useCovariateMeasurementCount365d = TRUE,
                                                              useCovariateMeasurementBelow = TRUE,
                                                              useCovariateMeasurementAbove = TRUE,
                                                              useCovariateConceptCounts = TRUE,
                                                              useCovariateRiskScores = TRUE,
                                                              useCovariateRiskScoresCharlson = TRUE,
                                                              useCovariateRiskScoresDCSI = TRUE,
                                                              useCovariateRiskScoresCHADS2 = TRUE,
                                                              useCovariateRiskScoresCHADS2VASc = TRUE,
                                                              useCovariateInteractionYear = FALSE,
                                                              useCovariateInteractionMonth = FALSE,
                                                              excludedCovariateConceptIds = c(),
                                                              deleteCovariatesSmallCount = 100)

  getDbCmDataArgs <- CohortMethod::createGetDbCohortMethodDataArgs(excludeDrugsFromCovariates = FALSE,
                                                                   covariateSettings = covarSettings)

  createStudyPopArgs1 <- CohortMethod::createCreateStudyPopulationArgs(removeDuplicateSubjects = TRUE,
                                                                       removeSubjectsWithPriorOutcome = TRUE,
                                                                       riskWindowStart = 0,
                                                                       riskWindowEnd = 0,
                                                                       addExposureDaysToEnd = TRUE,
                                                                       minDaysAtRisk = 1)

  createStudyPopArgs2 <- CohortMethod::createCreateStudyPopulationArgs(removeDuplicateSubjects = TRUE,
                                                                       removeSubjectsWithPriorOutcome = TRUE,
                                                                       riskWindowStart = 0,
                                                                       riskWindowEnd = 99999,
                                                                       addExposureDaysToEnd = FALSE,
                                                                       minDaysAtRisk = 1)

  # Fixing seed for reproducability:
  createPsArgs <- CohortMethod::createCreatePsArgs(control = Cyclops::createControl(noiseLevel = "silent",
                                                                                    cvType = "auto",
                                                                                    tolerance = 2e-07,
                                                                                    cvRepetitions = 10,
                                                                                    startingVariance = 0.01,
                                                                                    seed = 123))

  matchOnPsArgs1 <- CohortMethod::createMatchOnPsArgs(maxRatio = 1)

  matchOnPsArgs2 <- CohortMethod::createMatchOnPsArgs(maxRatio = 100)

  fitOutcomeModelArgs1 <- CohortMethod::createFitOutcomeModelArgs(stratified = FALSE,
                                                                  useCovariates = FALSE,
                                                                  modelType = "cox")

  fitOutcomeModelArgs2 <- CohortMethod::createFitOutcomeModelArgs(stratified = TRUE,
                                                                  useCovariates = FALSE,
                                                                  modelType = "cox")

  # Fixing seed for reproducability
  fitOutcomeModelArgs3 <- CohortMethod::createFitOutcomeModelArgs(stratified = TRUE,
                                                                  useCovariates = TRUE,
                                                                  modelType = "cox",
                                                                  control = Cyclops::createControl(cvType = "auto",
                                                                                                   startingVariance = 0.01,
                                                                                                   tolerance = 2e-07,
                                                                                                   cvRepetitions = 10,
                                                                                                   selectorType = "byPid",
                                                                                                   noiseLevel = "quiet",
                                                                                                   seed = 123))

  cmAnalysis1 <- CohortMethod::createCmAnalysis(analysisId = 1,
                                                description = "No matching, simple outcome model, per protocol",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs1,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs1)

  cmAnalysis2 <- CohortMethod::createCmAnalysis(analysisId = 2,
                                                description = "1-on-1 matching plus simple conditioned outcome model, per protocol",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs1,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs1,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs2)

  cmAnalysis3 <- CohortMethod::createCmAnalysis(analysisId = 3,
                                                description = "Variable ratio matching plus simple conditioned outcome model, per protocol",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs1,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs2,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs2)

  cmAnalysis4 <- CohortMethod::createCmAnalysis(analysisId = 4,
                                                description = "Variable ratio matching plus full outcome model, per protocol",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs1,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs2,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs3)

  cmAnalysis5 <- CohortMethod::createCmAnalysis(analysisId = 5,
                                                description = "No matching, simple outcome model, intent-to-treat",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs2,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs1)

  cmAnalysis6 <- CohortMethod::createCmAnalysis(analysisId = 6,
                                                description = "1-on-1 matching plus simple conditioned outcome model, intent-to-treat",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs2,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs1,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs2)

  cmAnalysis7 <- CohortMethod::createCmAnalysis(analysisId = 7,
                                                description = "Variable ratio matching plus simple conditioned outcome model, intent-to-treat",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs2,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs2,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs2)

  cmAnalysis8 <- CohortMethod::createCmAnalysis(analysisId = 8,
                                                description = "Variable ratio matching plus full outcome model, intent-to-treat",
                                                getDbCohortMethodDataArgs = getDbCmDataArgs,
                                                createStudyPopArgs = createStudyPopArgs2,
                                                createPs = TRUE,
                                                createPsArgs = createPsArgs,
                                                matchOnPs = TRUE,
                                                matchOnPsArgs = matchOnPsArgs2,
                                                fitOutcomeModel = TRUE,
                                                fitOutcomeModelArgs = fitOutcomeModelArgs3)

  cmAnalysisList <- list(cmAnalysis1,
                         cmAnalysis2,
                         cmAnalysis3,
                         cmAnalysis4,
                         cmAnalysis5,
                         cmAnalysis6,
                         cmAnalysis7,
                         cmAnalysis8)

  CohortMethod::saveCmAnalysisList(cmAnalysisList, file.path(outputFolder, "cmAnalysisList.txt"))
  CohortMethod::saveDrugComparatorOutcomesList(drugComparatorOutcomesList,
                                               file.path(outputFolder,
                                                         "drugComparatorOutcomesList.txt"))
}
